### ISSUE TITLE
Cannot connect MCS or Telescope to power via wires

### ISSUE THREAD

**Issue by PLUS-dextra** [igentuman/GalacticResearch#21]
Battery slot tooltip in the GUI's for the MCS and the Telescope says you can use a connected power source. This does not work. Not being able to use anything but 15k gJ batteries makes using this mod ridiculous, having to fill 20+ batteries at once and frantically swap them out as each machine runs.
![image](https://github.com/igentuman/GalacticResearch/assets/42011531/e880ab15-b70c-469e-97a4-214f4c6999b4)
![image](https://github.com/igentuman/GalacticResearch/assets/42011531/5e85fe9e-83fc-499f-87bd-79e9cd3ca628)

**Comment by igentuman** [comment]
I know this need to be improved, but wires are pluggable from one side
![image](https://github.com/igentuman/GalacticResearch/assets/4759881/27958ebe-6eb8-481f-8cc5-47c317f07bf2)
