### ISSUE TITLE
Crashed when GC and ExtraPlanets installed

### ISSUE THREAD

**Issue by HaHaWTH** [igentuman/GalacticResearch#6]
Environment：Forge 14.23.5.2860 JDK8u351
Install GC and ExtraPlanets together
Game crashed but didnt close when enter singleplayer world
[crash-2023-02-15_18.42.50-client.txt](https://github.com/igentuman/GalacticResearch/files/10742339/crash-2023-02-15_18.42.50-client.txt)

**Comment by HaHaWTH** [comment]
The Galactic research mod version is release 1.0,the latest version

**Comment by HaHaWTH** [comment]
> The Galactic research mod version is release 1.0,the latest version

This mod also causes serious FPS lag,after remove this mod and its dependencies this problem wont appear anymore

**Comment by igentuman** [comment]
fixed
